import { bg, backdrop } from './../../images/IndexImages';

export const styles = {
    container: {
      backgroundImage: `url(${bg})`,
      height: '90vh',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      zIndex: 5,
      position: 'relative',
    },
    content: {
      height: '100%',
      width: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      color: 'white',
    },
    sectionRed: {
      marginTop: -300,
      height: 1080,
      width: '90%',
      backgroundImage: `url(${backdrop})`,
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundColor: '#cf0820',
      backgroundAttachment: 'fixed',
      transform: `rotate(45deg)`,
      zIndex: 4,
      position: 'static',
      overflowX: 'hidden',
    },
    sectionBlack: {
      height: 1080,
      width: '90%',
      backgroundImage: `url(${backdrop})`,
      backgroundPosition: `-171px 621px`,
      backgroundRepeat: 'no-repeat',
      backgroundColor: 'black',
      backgroundAttachment: 'fixed',
      transform: `rotate(45deg)`,
      zIndex: 4,
      position: 'static',
      overflowX: 'hidden',
    },
    sectionYellow: {
      height: 1080,
      width: '90%',
      backgroundImage: `url(${backdrop})`,
      backgroundPosition: `-171px 613px`,
      backgroundRepeat: 'no-repeat',
      backgroundColor: '#fcd20e',
      backgroundAttachment: 'fixed',
      transform: `rotate(45deg)`,
      zIndex: 4,
      position: 'static',
      left: -300,
      overflowX: 'hidden',
    },
    sectionLast: {
      height: 1080,
      backgroundColor: '#fcd20e',
      zIndex: 5,
      position: 'static',
    //   backgroundImage: `url(${backdrop})`,
    //   backgroundPosition: 'left',
    //   backgroundRepeat: 'no-repeat',
    },
  }
